package codes;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class Anggota extends javax.swing.JInternalFrame {

    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form FormDua
     */
    public Anggota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kategori = new javax.swing.ButtonGroup();
        edit_btn = new javax.swing.JButton();
        hapus_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cari_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        npm_option = new javax.swing.JRadioButton();
        nama_option = new javax.swing.JRadioButton();
        jurusan_option = new javax.swing.JRadioButton();
        cari_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        noid_text = new javax.swing.JTextField();
        nmlengkap_text = new javax.swing.JTextField();
        jk_text = new javax.swing.JTextField();
        jurusan_text = new javax.swing.JTextField();
        thnangkatan_text = new javax.swing.JTextField();
        simpan_btn = new javax.swing.JButton();
        clear_btn1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat_text = new javax.swing.JTextArea();
        showall_btn = new javax.swing.JButton();
        tambah_btn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Data Anggota");
        setVisible(true);

        edit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/note-outlined-symbol.png"))); // NOI18N
        edit_btn.setText("Edit");
        edit_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edit_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        hapus_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recycling-bin.png"))); // NOI18N
        hapus_btn.setText("Hapus");
        hapus_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hapus_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        hapus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Cari Anggota");

        jLabel2.setText("Berdasarkan :");

        // membuat tampilan model tabel
        model.addColumn("No");
        model.addColumn("NPM");
        model.addColumn("Nama Lengkap");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Jurusan");
        model.addColumn("Tahun Angkatan");
        model.addColumn("Alamat");

        //menampilkan data database ke dalam tabel
        try {
            int no = 1;
            String sql = "select * from member";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{no++, res.getString(1), res.getString(2),
                    res.getString(3), res.getString(4), res.getString(5),
                    res.getString(6)});
        }

    } catch (SQLException e) {
    }

    jTable1.setModel(model);
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    kategori.add(npm_option);
    npm_option.setText("NPM");
    npm_option.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            npm_optionActionPerformed(evt);
        }
    });

    kategori.add(nama_option);
    nama_option.setText("Nama");

    kategori.add(jurusan_option);
    jurusan_option.setText("Jurusan");

    cari_btn.setText("Cari");
    cari_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cari_btnActionPerformed(evt);
        }
    });

    clear_btn.setText("Hapus");
    clear_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            clear_btnActionPerformed(evt);
        }
    });

    jPanel1.setBackground(new java.awt.Color(204, 204, 204));
    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas Anggota"));

    jLabel3.setText("NPM");

    jLabel4.setText("Nama Lengkap");

    jLabel5.setText("Jenis Kelamin");

    jLabel6.setText("Jurusan");

    jLabel7.setText("Tahun Angkatan");

    jLabel8.setText("Alamat");

    noid_text.setEnabled(false);
    noid_text.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            noid_textActionPerformed(evt);
        }
    });

    nmlengkap_text.setEnabled(false);

    jk_text.setEnabled(false);

    jurusan_text.setEnabled(false);

    thnangkatan_text.setEnabled(false);

    simpan_btn.setText("Simpan");
    simpan_btn.setEnabled(false);
    simpan_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            simpan_btnActionPerformed(evt);
        }
    });

    clear_btn1.setText("Bersihkan");
    clear_btn1.setEnabled(false);
    clear_btn1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            clear_btn1ActionPerformed(evt);
        }
    });

    alamat_text.setColumns(20);
    alamat_text.setRows(5);
    alamat_text.setEnabled(false);
    jScrollPane2.setViewportView(alamat_text);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8)
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel7)
                .addComponent(jLabel4)
                .addComponent(jLabel3))
            .addGap(29, 29, 29)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(noid_text, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addComponent(nmlengkap_text, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addComponent(jurusan_text)
                .addComponent(thnangkatan_text)
                .addComponent(jk_text)
                .addComponent(jScrollPane2))
            .addGap(0, 13, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(simpan_btn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(clear_btn1)
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(noid_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(nmlengkap_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jk_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jurusan_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(thnangkatan_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(simpan_btn)
                .addComponent(clear_btn1))
            .addGap(23, 23, 23))
    );

    showall_btn.setText("Tampilkan Semua");
    showall_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            showall_btnActionPerformed(evt);
        }
    });

    tambah_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-circular-outlined-button.png"))); // NOI18N
    tambah_btn.setText("Tambah");
    tambah_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    tambah_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tambah_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tambah_btnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(npm_option)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nama_option)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jurusan_option))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(cari_text, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cari_btn)
                                    .addGap(18, 18, 18)
                                    .addComponent(clear_btn)
                                    .addGap(18, 18, 18)
                                    .addComponent(showall_btn)))
                            .addGap(0, 120, Short.MAX_VALUE))
                        .addComponent(jScrollPane1)))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tambah_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(hapus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cari_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showall_btn)
                        .addComponent(cari_btn)
                        .addComponent(clear_btn)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(npm_option)
                        .addComponent(nama_option)
                        .addComponent(jurusan_option)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tambah_btn)
                .addComponent(edit_btn)
                .addComponent(hapus_btn))
            .addContainerGap(78, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        simpan_btn.setText("Update");
        Editable();
    }//GEN-LAST:event_edit_btnActionPerformed

    private void hapus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_btnActionPerformed

        int option = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {

            // fungsi hapus data
            try {

                String sql = "delete from member where no_id='" + noid_text.getText() + "'";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            HapusIsian();
            NonEditable();
            GetData();
        }
    }//GEN-LAST:event_hapus_btnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // menampilkan data ke dalam form pengisian:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String idbuku_temp = jTable1.getValueAt(baris, 1).toString();
        noid_text.setText(idbuku_temp);

        String judulbuku_temp = jTable1.getValueAt(baris, 2).toString();
        nmlengkap_text.setText(judulbuku_temp);

        String pengarang_temp = jTable1.getValueAt(baris, 3).toString();
        jk_text.setText(pengarang_temp);

        String penerbit_temp = jTable1.getValueAt(baris, 4).toString();
        jurusan_text.setText(penerbit_temp);

        String cetakan_temp = jTable1.getValueAt(baris, 5).toString();
        thnangkatan_text.setText(cetakan_temp);

        String alamat_temp = jTable1.getValueAt(baris, 6).toString();
        alamat_text.setText(alamat_temp);

    }//GEN-LAST:event_jTable1MouseClicked

    private void npm_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npm_optionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npm_optionActionPerformed

    private void cari_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_btnActionPerformed
        if (!(npm_option.isSelected() || nama_option.isSelected() || jurusan_option.isSelected())) {
            JOptionPane.showMessageDialog(null, "Pilih kategori terlebih dahulu");
        } else {
            while (model.getRowCount() > 0) {
                for (int i = 0; i < model.getRowCount(); ++i) {
                    model.removeRow(i);
                }
            }

            //menampilkan data database ke dalam tabel
            String sql = null;
            try {

                int no = 1;
                if (npm_option.isSelected()) {
                    sql = "select * from member where no_id REGEXP '" + cari_text.getText() + ".*'";
                } else if (nama_option.isSelected()) {
                    sql = "select * from member where nama_lengkap REGEXP '" + cari_text.getText() + ".*'";
                } else {
                    sql = "select * from member where jurusan REGEXP '" + cari_text.getText() + ".*'";
                }
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                while (res.next()) {
                    model.addRow(new Object[]{no++, res.getString(1), res.getString(2),
                        res.getString(3), res.getString(4), res.getString(5),
                        res.getString(6)});
                }
                jTable1.setModel(model);
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_cari_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        cari_text.setText("");
        kategori.clearSelection();
    }//GEN-LAST:event_clear_btnActionPerformed

    private void showall_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showall_btnActionPerformed
        GetData();
        cari_text.setText("");
        kategori.clearSelection();
    }//GEN-LAST:event_showall_btnActionPerformed

    private void tambah_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_btnActionPerformed
        simpan_btn.setText("Simpan");
        HapusIsian();
        Editable();
    }//GEN-LAST:event_tambah_btnActionPerformed

    private void clear_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btn1ActionPerformed
        HapusIsian();
        NonEditable();
    }//GEN-LAST:event_clear_btn1ActionPerformed

    private void simpan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_btnActionPerformed

        if (simpan_btn.getText().equals("Update")) {
            // Edit Data
            try {
                String sql = "UPDATE member SET no_id = '" + noid_text.getText() + "', nama_lengkap = '" + nmlengkap_text.getText()
                        + "', jenis_kelamin = '" + jk_text.getText() + "',jurusan = '" + jurusan_text.getText()
                        + "',tahun_angkatan = '" + thnangkatan_text.getText() + "',alamat = '" + alamat_text.getText()
                        + "' WHERE no_id = '" + noid_text.getText() + "'";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil diedit");
                GetData();
                HapusIsian();
                NonEditable();
                simpan_btn.setText("Simpan");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Perubahan Data Gagal" + e.getMessage());
            }
        } else {
            try {
                String sql = "INSERT INTO member VALUES ('" + noid_text.getText() + "','" + nmlengkap_text.getText()
                        + "','" + jk_text.getText() + "','" + jurusan_text.getText() + "','"
                        + thnangkatan_text.getText() + "','" + alamat_text.getText()
                        + "')";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
                GetData();
                HapusIsian();
                NonEditable();
                simpan_btn.setText("Simpan");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_simpan_btnActionPerformed

    private void noid_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noid_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noid_textActionPerformed

    private void HapusIsian() {
        noid_text.setText("");
        nmlengkap_text.setText("");
        jk_text.setText("");
        jurusan_text.setText("");
        thnangkatan_text.setText("");
        alamat_text.setText("");
    }

    private void Editable() {
        noid_text.setEnabled(true);
        nmlengkap_text.setEnabled(true);
        jk_text.setEnabled(true);
        jurusan_text.setEnabled(true);
        thnangkatan_text.setEnabled(true);
        alamat_text.setEnabled(true);
        simpan_btn.setEnabled(true);
        clear_btn1.setEnabled(true);
    }

    private void NonEditable() {
        noid_text.setEnabled(false);
        nmlengkap_text.setEnabled(false);
        jk_text.setEnabled(false);
        jurusan_text.setEnabled(false);
        thnangkatan_text.setEnabled(false);
        alamat_text.setEnabled(false);
        simpan_btn.setEnabled(false);
        clear_btn1.setEnabled(false);
    }

    protected void GetData() {
        // ngapus semua data yg ada di dalam tabel. Dibersihin gitu
        while (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); ++i) {
                model.removeRow(i);
            }
        }
        //menampilkan data database baru yg udah ke-update ke dalam tabel
        try {
            int no = 1;
            String sql = "select * from member";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{no++, res.getString(1), res.getString(2),
                    res.getString(3), res.getString(4), res.getString(5),
                    res.getString(6)});
            }
            jTable1.setModel(model);
        } catch (SQLException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat_text;
    private javax.swing.JButton cari_btn;
    private javax.swing.JTextField cari_text;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton clear_btn1;
    private javax.swing.JButton edit_btn;
    private javax.swing.JButton hapus_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jk_text;
    private javax.swing.JRadioButton jurusan_option;
    private javax.swing.JTextField jurusan_text;
    private javax.swing.ButtonGroup kategori;
    private javax.swing.JRadioButton nama_option;
    private javax.swing.JTextField nmlengkap_text;
    private javax.swing.JTextField noid_text;
    private javax.swing.JRadioButton npm_option;
    private javax.swing.JButton showall_btn;
    private javax.swing.JButton simpan_btn;
    private javax.swing.JButton tambah_btn;
    private javax.swing.JTextField thnangkatan_text;
    // End of variables declaration//GEN-END:variables
}
