package codes;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
//import images.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class MenuUtama extends javax.swing.JFrame {

    // Bikin objek dari kelas lain buat nantinya bisa dipanggil
    Buku form1 = new Buku();
    Anggota form2 = new Anggota();
    Peminjaman pinjam = new Peminjaman();
    Pengembalian balik = new Pengembalian();
    LoginForm login = new LoginForm();
    Tanggal tanggal = new Tanggal(); // Ada di bawah class ini

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        BelumLogin();
        /* Set tampilan awal. Semua button kedisable kecuali 
        * button exit sama menu login 
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dataanggota_btn = new javax.swing.JButton();
        databuku_btn = new javax.swing.JButton();
        pinjam_btn = new javax.swing.JButton();
        keluar_btn = new javax.swing.JButton();
        balik_btn = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        user_menu = new javax.swing.JMenu();
        login_menuitem = new javax.swing.JMenuItem();
        logout_menuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perpustakaan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dataanggota_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users-group (1).png"))); // NOI18N
        dataanggota_btn.setText("Data Anggota");
        dataanggota_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dataanggota_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dataanggota_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataanggota_btnActionPerformed(evt);
            }
        });

        databuku_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books-stack-of-three (1).png"))); // NOI18N
        databuku_btn.setText("Data Buku");
        databuku_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        databuku_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        databuku_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databuku_btnActionPerformed(evt);
            }
        });

        pinjam_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.png"))); // NOI18N
        pinjam_btn.setText("Peminjaman");
        pinjam_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pinjam_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pinjam_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjam_btnActionPerformed(evt);
            }
        });

        keluar_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        keluar_btn.setText("Keluar dari aplikasi");
        keluar_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        keluar_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        keluar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar_btnActionPerformed(evt);
            }
        });

        balik_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book (1).png"))); // NOI18N
        balik_btn.setText("Pengembalian");
        balik_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        balik_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        balik_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balik_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4772, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2648, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataanggota_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(databuku_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pinjam_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(balik_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(keluar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(keluar_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataanggota_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(databuku_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pinjam_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(balik_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.getAccessibleContext().setAccessibleName("");

        user_menu.setText("User");

        login_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        login_menuitem.setText("Login");
        login_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_menuitemActionPerformed(evt);
            }
        });
        user_menu.add(login_menuitem);

        logout_menuitem.setText("Logout");
        logout_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_menuitemActionPerformed(evt);
            }
        });
        user_menu.add(logout_menuitem);

        jMenuBar1.add(user_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("Aplikasi Perpustakaan XX");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_menuitemActionPerformed
        login.setVisible(true); // nampilin window login
        this.hide(); // window menu utama 'hilang'
    }//GEN-LAST:event_login_menuitemActionPerformed

    private void logout_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_menuitemActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Anda yakin ingin logout?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            BelumLogin(); /* Kalo klik yes di pop up dialog box, semuanya balik
            kayak waktu tampilan awal pas dirun
            */
        }
    }//GEN-LAST:event_logout_menuitemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); /* set biar window menu 
        utama ukurannya full window
        */
    }//GEN-LAST:event_formWindowOpened

    private void balik_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balik_btnActionPerformed
        jDesktopPane1.removeAll(); // 'Close semua JInternalFrame yg ada di jDesktopPane1
        jDesktopPane1.updateUI();
        jDesktopPane1.add(balik);
        balik.setVisible(true);
        try {
            balik.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_balik_btnActionPerformed

    private void keluar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar_btnActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Anda yakin ingin keluar dari aplikasi ini?", 
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0); // Keluar dari program
        }
    }//GEN-LAST:event_keluar_btnActionPerformed

    private void pinjam_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjam_btnActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.updateUI();
        jDesktopPane1.add(pinjam);
        pinjam.setVisible(true);
        try {
            pinjam.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pinjam_btnActionPerformed

    private void databuku_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databuku_btnActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.updateUI();
        jDesktopPane1.add(form1);
        form1.setVisible(true);
        try {
            form1.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_databuku_btnActionPerformed

    private void dataanggota_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataanggota_btnActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.updateUI();
        jDesktopPane1.add(form2);
        form2.setVisible(true);
        try {
            form2.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dataanggota_btnActionPerformed

    private void BelumLogin() {
        login_menuitem.setEnabled(true);
        logout_menuitem.setEnabled(false);
        databuku_btn.setEnabled(false);
        dataanggota_btn.setEnabled(false);
        pinjam_btn.setEnabled(false);
        balik_btn.setEnabled(false);
        jDesktopPane1.removeAll();
        jDesktopPane1.updateUI();
    }

    void SudahLogin() {
        login_menuitem.setEnabled(false);
        logout_menuitem.setEnabled(true);
        databuku_btn.setEnabled(true);
        dataanggota_btn.setEnabled(true);
        pinjam_btn.setEnabled(true);
        balik_btn.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuUtama().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balik_btn;
    private javax.swing.JButton dataanggota_btn;
    private javax.swing.JButton databuku_btn;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluar_btn;
    private javax.swing.JMenuItem login_menuitem;
    private javax.swing.JMenuItem logout_menuitem;
    private javax.swing.JButton pinjam_btn;
    private javax.swing.JMenu user_menu;
    // End of variables declaration//GEN-END:variables

}

class Tanggal {
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();
        
    public String getTanggal() {
        return dateFormat.format(date);
    }

    public String tambahTanggal() {
        int tambah = 7;
        Calendar calTambah = Calendar.getInstance();
        calTambah.setTime(date);
        calTambah.add(Calendar.DAY_OF_MONTH, tambah);
        return dateFormat.format(calTambah.getTime());
    }
}
