/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codes;

import java.awt.Container;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Peminjaman extends javax.swing.JInternalFrame {

    Tanggal tanggal = new Tanggal();
    private int no = 1;
    private int noTransak = 0000;
    private String idbuku_semua[];
    

    /**
     * Creates new form Peminjaman
     */
    public Peminjaman() {
        initComponents();
        tanggalpinjam_text.setText(tanggal.getTanggal());
        tanggalbalik_text.setText(tanggal.tambahTanggal());
        setNoTransaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nopinjam_text = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        npm_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jurusanpeminjam_text = new javax.swing.JTextField();
        namapeminjam_text = new javax.swing.JTextField();
        caripeminjam_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pengarang_text = new javax.swing.JTextField();
        noidbuku_text = new javax.swing.JTextField();
        judulbuku_text = new javax.swing.JTextField();
        caribuku_btn = new javax.swing.JButton();
        tambahbuku_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        simpan_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        showall_btn = new javax.swing.JButton();
        tanggalpinjam_text = new javax.swing.JTextField();
        tanggalbalik_text = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Peminjaman");
        setVisible(true);

        jLabel1.setText("Nomor Peminjaman");

        nopinjam_text.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Peminjam"));

        jLabel2.setText("NPM");

        jLabel3.setText("Nama");

        jLabel4.setText("Jurusan");

        jurusanpeminjam_text.setEnabled(false);

        namapeminjam_text.setEnabled(false);

        caripeminjam_btn.setText("Cari");
        caripeminjam_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caripeminjam_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(npm_text, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(caripeminjam_btn)
                                .addGap(0, 201, Short.MAX_VALUE))
                            .addComponent(namapeminjam_text)
                            .addComponent(jurusanpeminjam_text, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(npm_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caripeminjam_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namapeminjam_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jurusanpeminjam_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Buku"));

        jLabel5.setText("No ID");

        jLabel10.setText("Judul Buku");

        jLabel11.setText("Pengarang");

        pengarang_text.setEnabled(false);

        judulbuku_text.setEnabled(false);

        caribuku_btn.setText("Cari Buku");
        caribuku_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribuku_btnActionPerformed(evt);
            }
        });

        tambahbuku_btn.setText("Tambah");
        tambahbuku_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahbuku_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(pengarang_text))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(noidbuku_text, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(caribuku_btn)
                                .addGap(0, 14, Short.MAX_VALUE))
                            .addComponent(judulbuku_text)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tambahbuku_btn)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(noidbuku_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caribuku_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(judulbuku_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pengarang_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tambahbuku_btn))
        );

        jLabel12.setText("Tanggal Peminjaman");

        jLabel13.setText("Tanggal Pengembalian");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Buku Peminjaman"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "No", "No ID", "Judul Buku", "Pengarang"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        simpan_btn.setText("Simpan");
        simpan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_btnActionPerformed(evt);
            }
        });

        cancel_btn.setText("Cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        showall_btn.setText("Tampilkan Semua Data Peminjaman");
        showall_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showall_btnActionPerformed(evt);
            }
        });

        tanggalpinjam_text.setEnabled(false);

        tanggalbalik_text.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showall_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpan_btn)
                        .addGap(18, 18, 18)
                        .addComponent(cancel_btn))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nopinjam_text, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanggalpinjam_text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanggalbalik_text)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nopinjam_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(tanggalpinjam_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalbalik_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan_btn)
                    .addComponent(cancel_btn)
                    .addComponent(showall_btn))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caripeminjam_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caripeminjam_btnActionPerformed
        try {

            String sql = "select * from member where no_id= '" + npm_text.getText() + "'";

            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {

                namapeminjam_text.setText(res.getString("nama_lengkap"));
                jurusanpeminjam_text.setText(res.getString("jurusan"));
            }
            if(namapeminjam_text.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data anggota tidak ditemukan");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "GAGAL");
        }
    }//GEN-LAST:event_caripeminjam_btnActionPerformed

    private void caribuku_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribuku_btnActionPerformed
        try {

            String sql = "select * from buku where id_buku= '" + noidbuku_text.getText() + "'";

            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {

                judulbuku_text.setText(res.getString("nama_buku"));
                pengarang_text.setText(res.getString("pengarang"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "GAGAL");
        }
    }//GEN-LAST:event_caribuku_btnActionPerformed

    private void tambahbuku_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahbuku_btnActionPerformed
        DefaultTableModel dataModel = (DefaultTableModel) jTable1.getModel();
        List list = new ArrayList<>();

        jTable1.setAutoCreateColumnsFromModel(true);
        list.add(no++);
        list.add(noidbuku_text.getText());
        list.add(judulbuku_text.getText());
        list.add(pengarang_text.getText());
        dataModel.addRow(list.toArray());
        
        noidbuku_text.setText("");
        judulbuku_text.setText("");
        pengarang_text.setText("");
    }//GEN-LAST:event_tambahbuku_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        HapusIsian();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void showall_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showall_btnActionPerformed
        Container parent = this.getParent();
        DataPeminjaman allpinjam = new DataPeminjaman();
        parent.add(allpinjam);
        allpinjam.setVisible(true);
    }//GEN-LAST:event_showall_btnActionPerformed

    private void simpan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_btnActionPerformed
        // ngambil id buku yg dipinjam dari table
        int i;
        int jumbuk = 0;
        String kump_idbuku = "";
        for (i = 0; i <= jTable1.getRowCount() - 1; i++) {
            String idbuku_pinjam = jTable1.getValueAt(i, 1).toString();
            String sql = null;

            try {
                sql = "SELECT stock FROM buku WHERE id_buku = '" + idbuku_pinjam + "'";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                res.next();
                int stock_temp = res.getInt("stock") - 1;

                try {
                    sql = "UPDATE buku SET stock = '" + stock_temp + "' WHERE id_buku = '" + idbuku_pinjam + "'";
                    conn = (Connection) Config.configDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
//                    JOptionPane.showMessageDialog(null, "Perubahan Data Stock Berhasil");
                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(null, "Perubahan Data Stock Gagal" + e.getMessage());
                }
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Pengambilan data gagal " + e.getMessage());
            }
            jumbuk += 1;
            kump_idbuku += idbuku_pinjam + " ";
        }
//        System.out.println(kump_idbuku);
        // Nyimpen data peminjaman
        try {
            String sql = "INSERT INTO pinjam VALUES ('" + nopinjam_text.getText() + "','" + npm_text.getText()
                    + "','" + namapeminjam_text.getText() + "','" + jumbuk + "','" + tanggalpinjam_text.getText() + "','" + tanggalbalik_text.getText() + "','" + kump_idbuku + "', NULL, 0)";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        HapusIsian();
        setNoTransaksi();
    }//GEN-LAST:event_simpan_btnActionPerformed

    private void HapusIsian() {
        noidbuku_text.setText("");
        judulbuku_text.setText("");
        pengarang_text.setText("");

        nopinjam_text.setText("");
        npm_text.setText("");
        namapeminjam_text.setText("");
        jurusanpeminjam_text.setText("");

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        while (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); ++i) {
                model.removeRow(i);
            }
        }
    }

    private void setNoTransaksi() {
        String sql = null;
        String nopinjam_temp = "0000";
        java.sql.ResultSet res = null;
        try {
            sql = "SELECT no_pinjam FROM pinjam ORDER BY no_pinjam DESC LIMIT 1";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            res = stm.executeQuery(sql);
//            res.next();
            
            if(!res.next()) {
                nopinjam_text.setText("0001");
            } else {
            nopinjam_temp = res.getString("no_pinjam");
            

            int kode = Integer.parseInt(nopinjam_temp) + 1;
            nopinjam_temp = String.format("%04d", kode);

            nopinjam_text.setText(nopinjam_temp);  }
        } catch (SQLException e) {
//            if (res == null) {
//                nopinjam_text.setText("0001");
//            }
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton caribuku_btn;
    private javax.swing.JButton caripeminjam_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField judulbuku_text;
    private javax.swing.JTextField jurusanpeminjam_text;
    private javax.swing.JTextField namapeminjam_text;
    private javax.swing.JTextField noidbuku_text;
    private javax.swing.JTextField nopinjam_text;
    private javax.swing.JTextField npm_text;
    private javax.swing.JTextField pengarang_text;
    private javax.swing.JButton showall_btn;
    private javax.swing.JButton simpan_btn;
    private javax.swing.JButton tambahbuku_btn;
    private javax.swing.JTextField tanggalbalik_text;
    private javax.swing.JTextField tanggalpinjam_text;
    // End of variables declaration//GEN-END:variables
}
