/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codes;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Pengembalian extends javax.swing.JInternalFrame {

    Tanggal tanggal = new Tanggal();
    DefaultTableModel model = new DefaultTableModel();
    private int jumlahBuku, denda, kembali;
    private String id_books, hasil;
    private int no = 1;

    /**
     * Creates new form Pengembalian
     */
    public Pengembalian() {
        initComponents();
        tanggalbalik_text.setText(tanggal.getTanggal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        npm_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namapeminjam_text = new javax.swing.JTextField();
        caripeminjam_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nopinjam_text = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tanggaltempo_text = new javax.swing.JTextField();
        tanggalpinjam_text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tanggalbalik_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jumlahtelat_text = new javax.swing.JTextField();
        hitung_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        denda_text = new javax.swing.JTextField();
        simpan_btn = new javax.swing.JButton();
        batal_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dibayar_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kembalian_text = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pengembalian");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Peminjam"));

        jLabel3.setText("NPM");

        jLabel4.setText("Nama");

        namapeminjam_text.setEnabled(false);

        caripeminjam_btn.setText("Cari");
        caripeminjam_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caripeminjam_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(npm_text, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(caripeminjam_btn)
                                .addGap(0, 130, Short.MAX_VALUE))
                            .addComponent(namapeminjam_text))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(npm_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caripeminjam_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(namapeminjam_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Buku Peminjaman"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "No", "No ID", "Judul Buku", "Pengarang"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Peminjaman"));

        jLabel2.setText("Nomor Peminjaman");

        nopinjam_text.setEnabled(false);

        jLabel12.setText("Tanggal Peminjaman");

        jLabel13.setText("Tanggal Tempo");

        tanggaltempo_text.setEnabled(false);

        tanggalpinjam_text.setEnabled(false);

        jLabel1.setText("Tanggal Pengembalian");

        tanggalbalik_text.setEnabled(false);

        jLabel6.setText("Keterlambatan");

        jumlahtelat_text.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tanggaltempo_text, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(tanggalpinjam_text)
                    .addComponent(tanggalbalik_text)
                    .addComponent(jumlahtelat_text)
                    .addComponent(nopinjam_text))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nopinjam_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tanggalpinjam_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tanggaltempo_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tanggalbalik_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jumlahtelat_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        hitung_btn.setText("Hitung");
        hitung_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_btnActionPerformed(evt);
            }
        });

        jLabel5.setText("Denda");

        denda_text.setEnabled(false);

        simpan_btn.setText("Simpan");
        simpan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_btnActionPerformed(evt);
            }
        });

        batal_btn.setText("Batal");
        batal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_btnActionPerformed(evt);
            }
        });

        jLabel7.setText("Dibayar");

        jLabel8.setText("Kembali");

        kembalian_text.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(simpan_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(batal_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hitung_btn)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(denda_text, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kembalian_text)
                                    .addComponent(dibayar_text))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitung_btn)
                    .addComponent(jLabel5)
                    .addComponent(denda_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpan_btn)
                    .addComponent(batal_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dibayar_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kembalian_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caripeminjam_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caripeminjam_btnActionPerformed
        // Masukkin data dari database ke form
        try {

            String sql = "SELECT no_pinjam, nama_peminjam, jumlah_buku, tgl_pinjam, tgl_setkembali, idbooks FROM pinjam WHERE no_id LIKE '"
                    + npm_text.getText() + "' AND status LIKE '0'";

            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {

                namapeminjam_text.setText(res.getString("nama_peminjam"));
                nopinjam_text.setText(res.getString("no_pinjam"));
                tanggalpinjam_text.setText(res.getDate("tgl_pinjam").toString());
                tanggaltempo_text.setText(res.getDate("tgl_setkembali").toString());
                id_books = res.getString("idbooks");
                jumlahBuku = res.getInt("jumlah_buku");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        if(namapeminjam_text.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data peminjam tidak ditemukan");
        } else {
        // Ngitung Jumlah Telat
        String stglAwal = tanggaltempo_text.getText();
        String stglAkhir = tanggalbalik_text.getText();
        DateFormat dateAwal = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat dateAkhir = new SimpleDateFormat("yyyy-MM-dd");

        try {
            java.util.Date tglAwal = dateAwal.parse(stglAwal);
            java.util.Date tglAkhir = dateAkhir.parse(stglAkhir);

            java.util.Date TGLAwal = tglAwal;
            java.util.Date TGLAkhir = tglAkhir;
            Calendar cal1 = Calendar.getInstance();
            cal1.setTime(TGLAwal);
            Calendar cal2 = Calendar.getInstance();
            cal2.setTime(TGLAkhir);

            hasil = String.valueOf(daysBetween(cal1, cal2));

//            System.out.println("Tanggal Awal  = " +stglAwal);
//            System.out.println("Tanggal Akhir = " +stglAkhir);
//            System.out.println("Selisih: " +hasil+ " hari");
            jumlahtelat_text.setText(hasil + " hari");

        } catch (ParseException e) {
            if (Integer.parseInt(hasil)<=0) {
                jumlahtelat_text.setText("-");
            } else {
            JOptionPane.showMessageDialog(null, "Tanggal salah \n" + e.getMessage()); }
        }

        // Ngitung denda
        if (Integer.parseInt(hasil) > 0) {
            denda = Integer.parseInt(hasil) * 500 * jumlahBuku;
            double denda_dbl = (double) denda;
            denda_text.setText(String.valueOf(UbahRupiah(denda_dbl)));
        }

//        System.out.println(id_books);
//        System.out.println(jumlahBuku);
        String[] kata = id_books.split(" ");
        no = 1;
        for (int i = 0; i < kata.length; i++) {
//            System.out.println(kata[i]);
            //menampilkan data database ke dalam tabel
            try {
                String sql = "select id_buku, nama_buku, pengarang from buku where id_buku ='" + kata[i] + "'";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                while (res.next()) {

                    DefaultTableModel dataModel = (DefaultTableModel) jTable1.getModel();
                    List list = new ArrayList<>();

                    jTable1.setAutoCreateColumnsFromModel(true);
                    list.add(no++);
                    list.add(res.getString("id_buku"));
                    list.add(res.getString("nama_buku"));
                    list.add(res.getString("pengarang"));
                    dataModel.addRow(list.toArray());
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Pengambilan data buku gagal \n" + e.getMessage());
            }
        }
        }
    }//GEN-LAST:event_caripeminjam_btnActionPerformed

    private void batal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_btnActionPerformed
        HapusIsian();
    }//GEN-LAST:event_batal_btnActionPerformed

    private void hitung_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung_btnActionPerformed
        kembali = Integer.parseInt(dibayar_text.getText().toString()) - denda;
        kembalian_text.setText(String.valueOf(UbahRupiah((double) kembali)));
    }//GEN-LAST:event_hitung_btnActionPerformed

    private void simpan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_btnActionPerformed
        // ngambil id buku yg dipinjam dari table
        int i;
        for (i = 0; i <= jTable1.getRowCount() - 1; i++) {
            String idbuku_pinjam = jTable1.getValueAt(i, 1).toString();
            String sql = null;

            try {
                sql = "SELECT stock FROM buku WHERE id_buku = '" + idbuku_pinjam + "'";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                res.next();
                int stock_temp = res.getInt("stock") + 1;

                try {
                    sql = "UPDATE buku SET stock = '" + stock_temp + "' WHERE id_buku = '" + idbuku_pinjam + "'";
                    conn = (Connection) Config.configDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
//                    JOptionPane.showMessageDialog(null, "Perubahan Data Stock Berhasil");
                } catch (HeadlessException | SQLException e) {
//                    JOptionPane.showMessageDialog(null, "Perubahan Data Stock Gagal" + e.getMessage());
                }
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Pengambilan data gagal " + e.getMessage());
            }

            // update status pengembalian
            try {
                sql = "UPDATE pinjam SET status = '1', denda = '" + denda + "' WHERE no_pinjam = '" + nopinjam_text.getText() + "'";
                Connection conn = (Connection) Config.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
//                    JOptionPane.showMessageDialog(null, "Perubahan Data Stock Berhasil");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Perubahan Data Peminjaman Gagal \n" + e.getMessage());
            }

//            jumbuk += 1;
//            kump_idbuku += idbuku_pinjam + " ";
        }
//        System.out.println(kump_idbuku);
        HapusIsian();
        JOptionPane.showMessageDialog(null, "Penyimpanan Berhasil");
    }//GEN-LAST:event_simpan_btnActionPerformed

    private static long daysBetween(Calendar tanggalAwal, Calendar tanggalAkhir) {
        long lama = 0;
        Calendar tanggal = (Calendar) tanggalAwal.clone();
        while (tanggal.before(tanggalAkhir)) {
            tanggal.add(Calendar.DAY_OF_MONTH, 1);
            lama++;
        }
        return lama;
    }
    
    private void HapusIsian() {
        tanggalpinjam_text.setText("");
        tanggaltempo_text.setText("");
        tanggalbalik_text.setText("");
        jumlahtelat_text.setText("");
        nopinjam_text.setText("");
        npm_text.setText("");
        namapeminjam_text.setText("");
        denda_text.setText("");
        dibayar_text.setText("");
        kembalian_text.setText("");

        model = (DefaultTableModel) jTable1.getModel();

        while (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); ++i) {
                model.removeRow(i);
            }
        }
    }
    
    public String UbahRupiah(double uang) {

        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        return kursIndonesia.format(uang);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal_btn;
    private javax.swing.JButton caripeminjam_btn;
    private javax.swing.JTextField denda_text;
    private javax.swing.JTextField dibayar_text;
    private javax.swing.JButton hitung_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlahtelat_text;
    private javax.swing.JTextField kembalian_text;
    private javax.swing.JTextField namapeminjam_text;
    private javax.swing.JTextField nopinjam_text;
    private javax.swing.JTextField npm_text;
    private javax.swing.JButton simpan_btn;
    private javax.swing.JTextField tanggalbalik_text;
    private javax.swing.JTextField tanggalpinjam_text;
    private javax.swing.JTextField tanggaltempo_text;
    // End of variables declaration//GEN-END:variables
}